// Generated by `npm run content -w @ball-knowledge/mobile` from the repo's content/ folder.
import bundle from '../generated/content.json';
import { loadBundle, type AppContent } from './bundle';

/** The content shipped with this build, validated once at startup. */
export const content: AppContent = loadBundle(bundle);
